//------------------------------------------------------------
// DONOT MODIFY THIS FILE
// generated by JISHENGJU automatically
//------------------------------------------------------------

#ifndef DDR_SYSREG_REG_SW_H
#define DDR_SYSREG_REG_SW_H

typedef union {
    struct {
        unsigned int rg_broadcast_mode : 1; // [0]
        unsigned int rg_ddrc_32en : 1; // [1]
        unsigned int RESERVED_0 : 2; // [3:2]
        unsigned int rg_ctl_ddr_usw_rst_reg : 28; // [31:4]
    };
    unsigned int u32;
} DDR_SYSREG_REG_SW_DDR_CFG0_U;

typedef union {
    volatile DDR_SYSREG_REG_SW_DDR_CFG0_U ddr_sysreg_registers_struct_ddr_cfg0;    // 0x0
} DDR_SYSREG_REG_SW_REG_S;
#endif

