//------------------------------------------------------------
// DONOT MODIFY THIS FILE
// generated by JISHENGJU automatically
//------------------------------------------------------------

#ifndef DWC_DDR_UMCTL2_C_STRUCT_H
#define DWC_DDR_UMCTL2_C_STRUCT_H

typedef union {
    struct {
        unsigned int operating_mode : 3; // [2:0]
        unsigned int Reserved_3_3 : 1; // [3]
        unsigned int selfref_type : 2; // [5:4]
        unsigned int Reserved_6_7 : 2; // [7:6]
        unsigned int selfref_state : 2; // [9:8]
        unsigned int Reserved_10_11 : 2; // [11:10]
        unsigned int selfref_cam_not_empty : 1; // [12]
        unsigned int Reserved_13_31 : 19; // [31:13]
    };
    unsigned int u32;
} DWC_DDR_UMCTL2_C_STRUCT_STAT_U;

typedef union {
    struct {
        unsigned int selfref_en : 1; // [0]
        unsigned int powerdown_en : 1; // [1]
        unsigned int deeppowerdown_en : 1; // [2]
        unsigned int en_dfi_dram_clk_disable : 1; // [3]
        unsigned int Reserved_4_4 : 1; // [4]
        unsigned int selfref_sw : 1; // [5]
        unsigned int stay_in_selfref : 1; // [6]
        unsigned int dis_cam_drain_selfref : 1; // [7]
        unsigned int lpddr4_sr_allowed : 1; // [8]
        unsigned int Reserved_9_31 : 23; // [31:9]
    };
    unsigned int u32;
} DWC_DDR_UMCTL2_C_STRUCT_PWRCTL_U;

typedef union {
    volatile DWC_DDR_UMCTL2_C_STRUCT_STAT_U dwc_ddr_umctl2_c_struct_stat;    // 0x4
    volatile DWC_DDR_UMCTL2_C_STRUCT_PWRCTL_U dwc_ddr_umctl2_c_struct_pwrctl;    // 0x30
} DWC_DDR_UMCTL2_C_STRUCT_REG_S;

#endif

