obj-$(CONFIG_SPL_THEAD_TH1520_DDR) += ddr_common_func.o
obj-$(CONFIG_SPL_THEAD_TH1520_DDR) += init_ddr.o
obj-$(CONFIG_SPL_THEAD_TH1520_DDR) += lpddr4_init.o
obj-$(CONFIG_SPL_THEAD_TH1520_DDR) += waitfwdone.o
