obj-$(CONFIG_SPL_THEAD_TH1520_DDR) += common_lib.o
obj-$(CONFIG_SPL_THEAD_TH1520_DDR) += ddr_common_func.o
obj-$(CONFIG_SPL_THEAD_TH1520_DDR) += ddr_retention.o
obj-$(CONFIG_SPL_THEAD_TH1520_DDR) += firmware.o
obj-$(CONFIG_SPL_THEAD_TH1520_DDR) += init_ddr.o
obj-$(CONFIG_SPL_THEAD_TH1520_DDR) += lpddr4_init.o
obj-$(CONFIG_SPL_THEAD_TH1520_DDR) += pinmux.o
obj-$(CONFIG_SPL_THEAD_TH1520_DDR) += waitfwdone.o
